### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by KeiMitchell** [KeiMichell/git-app#3]
# IPアドレス
175.41.205.216

**Comment by mutorisa** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、修正箇所ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！！

⭐️今後実装に関するご質問がございましたら、メンターに相談いただきますようお願いします。

**Comment by KeiMitchell** [comment]
ありがとうございます！！！！
